log_level: info
retry: 0
timeout: 3s
sleep: 0s
secret: "secret"
last_file_count: 10
max_hash_limit: 134217728
trash_save_time: 720h0m0s
trash_clear_cron: ""
image_target_size: 204800
jpeg_min_quality: 20
jpeg_max_quality: 80
image_save_format: 0
pull_sync_cron: ""
pull_sync_host: ""
pull_sync_secret: ""
push_sync_cron: ""
push_sync_host: ""
push_sync_secret: ""
