// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-12 15:26:44.9206148 +0800 CST m=+0.049000901

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/getFileCompleteInfo": {
            "get": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "getFileCompleteInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fileOrFolderPath",
                        "name": "fileOrFolderPath",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/listAllFileSimpleInfo": {
            "get": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "listAllFileSimpleInfo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/listFolderInfo": {
            "get": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "listFolderInfo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "folderPath",
                        "name": "folderPath",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/listLastFileInfo": {
            "get": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "listLastFileInfo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/pullSyncFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "pullSyncFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pullSyncHost",
                        "name": "pullSyncHost",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/pushSyncFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "pushSyncFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pushSyncHost",
                        "name": "pushSyncHost",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/receivePushSyncFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "receivePushSyncFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filePath",
                        "name": "filePath",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "md5",
                        "name": "md5",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/removeFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "removeFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filePath",
                        "name": "filePath",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/uploadFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "uploadFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filePath",
                        "name": "filePath",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/uploadUrl": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "uploadUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filePath",
                        "name": "filePath",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
